"""onetomany

Revision ID: f724b8fb9b8c
Revises: 14e60d763520
Create Date: 2024-02-23 21:39:45.487327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'f724b8fb9b8c'
down_revision: Union[str, None] = '14e60d763520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('key_name', sa.String(length=55), nullable=False))
    op.add_column('api_key', sa.Column('hashed_key', sa.String(length=1024), nullable=True))
    op.add_column('api_key', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_foreign_key(None, 'api_key', 'user', ['user_id'], ['id'], ondelete='Cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_key', type_='foreignkey')
    op.drop_column('api_key', 'user_id')
    op.drop_column('api_key', 'hashed_key')
    op.drop_column('api_key', 'key_name')
    # ### end Alembic commands ###
